### PR TITLE
Configure eslint, prettier and jest

### PR DESCRIPTION
**Pull request by yonas-seyoum**

### CODE REVIEW

**Review by leulsege — CHANGES_REQUESTED** [review]
I was comparing the .eslintrc.js file from service-core and lib-boilerplate folder,
the lib-boilerplate folder have no  "parser: '@typescript-eslint/parser'," 
so someone explain to me why that one faced no error but yours

**Comment by peterrogov** [comment]
I've just tried this branch on my computer, I opened .eslintrc.js and commented the line with parser as follows:
```js
module.exports = {
  // parser: '@typescript-eslint/parser',
  extends: '../../config/eslint-library.js', // Path to shared ESLint config
};
```

With this change, running `npm run lint` works fine and no problems.
Could you provide more details about the problem you had?

**Comment by peterrogov** [comment]
Also, another comment, the `eslint-library` file was made a shared config for libraries. React webapps a slightly different so I would actually recommend creating `config/eslint-react.js` file and place there a standard config for react projects. Then reuse it.

**Review by peterrogov — CHANGES_REQUESTED** [review]
Make a separate shared eslint config for react apps

**Comment by yonas-seyoum** [comment]
The problem is when I comment `parser: '@typescript-eslint/parser'`, the error message below kicks in
Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.js » ../../config/eslint-library.js': Cannot find module '@typescript-eslint/parser'.
And this is exactly what happened when I created an new pull request

**Review by peterrogov — APPROVED** [review]

**Review by leulsege — APPROVED** [review]

**Pull request merged**
